name: timecode
description: |
  This library is a pure Dart implementation of the SMTPE timecode specification.
  It is based on the pytimecode library by Joshua Banton.
  https://pypi.org/project/pytimecode.py/
version: 0.2.0
homepage: https://www.jeffmikels.com

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
